### ISSUE TITLE
README.md provides a wrong example

### ISSUE THREAD

**Issue by AlexanderMoskovkin** [crudo/grunt-testcafe#1]
Hi @crudo !

Thanks for your cool plugin.

But it seems that README.md provides a wrong example. The code doesn't work if I just copy-paste it.
However, it works if I write:

``` js
grunt.initConfig({
    testcafe: {
        'test-functional': {    // note this line
            options: {
                files:    ['tests/*.test.js'],
                browsers: ['chrome']
            }
        }
    }
});
```

**Comment by crudo** [comment]
Hi @AlexanderMoskovkin, thanks for noticing. It is fixed.
