### ISSUE TITLE
Cannot find module 'mkdirp'

### ISSUE THREAD

**Issue by minmur** [crudo/grunt-testcafe#19]
Hi.

Maybe it's a very basic thing and i'm just missing something, but can't make it run.
I have very simple test case and it runs perfectly when i run: `testcafe chrome e2e/test.js`

But when i try to run this grunt task:
```javascript
testcafe: {
      test: {
        options: {
          files: ['e2e/*.js'],
          browsers: ['chrome'],
          takeScreenshotsOnFail: true,
          screenshotsPath: 'e2e/screenshots',
        }
      }
    }
```

I get error:
`Loading "testcafe.js" tasks...ERROR
Error: Cannot find module 'mkdirp'`

What am i missing here? Should i install `mkdirp` as dev dependency?

node 4.7.2
testcafe 0.15.0 (tried both - global and local)
grunt 0.4.5
grunt-testcafe 0.15.0

**Comment by crudo** [comment]
Hi @minmur, thanks for the report. I will fix it on my side.
