### ISSUE TITLE
Add test run concurrency to list of available options

### ISSUE THREAD

**Issue by dsayerjp** [crudo/grunt-testcafe#23]
h2. Suggestion
Most TestCafe options are present in the grunt-testcafe package. One main thing that my team are missing are the ability to add test run concurrency to the grunt task.

h2. Expectation
Ideally, I'd like to be able to add the number of tests to run concurrently to the grunt testcafe options like: 

```
        options: {
          files: ['tests/web/*.js'],
          browsers: ['chrome'],
          takeScreenshotsOnFail: true,
          screenshotsPath: 'output/screenshots',
          skipJsErrors: true,
          concurrency: 3,
          quarantineMode: true,
          reporter: 'minimal'
        }

```

**Comment by crudo** [comment]
Hi @dsayerjp, will look at how we can add this option.

**Comment by crudo** [comment]
Fixed in https://github.com/crudo/grunt-testcafe/releases/tag/v0.18.6
