### ISSUE TITLE
Feature Request: Add screenshot path pattern

### ISSUE THREAD

**Issue by dsayerjp** [crudo/grunt-testcafe#26]
## Request Rationale

From TestCafe v0.21.0, you can specify a custom pattern to compose files' relative path and name. Having the ability to set this when running tests from Grunt would be advantagous. 

## Steps

I don't have access to create branches or PRs but I believe this would be the steps to do it:

Upgrade the referenced version of Testcafe in the `package.json` file to `v0.21.0`

File `tasks/testcafe.js` update `DEFAULT_OPTS` to:
(starting line 16)
```js
const DEFAULT_OPTS = {
    assertionTimeout: 3000,
    browsers: [],
    concurrency: 1,
    filter: null,
    quarantineMode: false,
    reporter: 'spec',
    screenshotsPath: null,
    screenshotPathPattern: null,
    selectorTimeout: 10000,
    skipJsErrors: false,
    speed: 1,
    startApp: { initDelay: 1000 },
    takeScreenshotsOnFail: false,
    proxyHost: null
};
```
and update the following (starting line 67) to:
```js
                return testCafeRunner
                    .useProxy(opts.proxyHost)
                    .src(files)
                    .browsers(opts.browsers)
                    .concurrency(opts.concurrency)
                    .filter(opts.filter)
                    .screenshots(opts.screenshotsPath, opts.takeScreenshotsOnFail, opts.screenshotPathPattern)
                    .reporter(opts.reporter, stream)
                    .run(opts);
```

Update the readme with
```md
#### screenshotsPathPattern

*Type*: `String`

*Default*: `null`

*Details*: [Screenshots path pattern](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-p---screenshot-path-pattern)

Specifies a custom pattern to compose screenshot files' relative path and name. This pattern overrides the default path pattern.
```

**Comment by crudo** [comment]
@dsayerjp Here you go: https://github.com/crudo/grunt-testcafe/releases/tag/v0.21.1 :)

**Comment by sarahncrowe** [comment]
@crudo I was having some trouble using screenshotsPathPattern, I wasn't noticing that the extra s in screenshots wasn't supposed to be there. May I suggest updating the README to display screenshotPathPattern instead? :)
