### ISSUE TITLE
outdated peer-dependency

### ISSUE THREAD

**Issue by japrescott** [crudo/grunt-testcafe#28]
there is a peerDependency listed in `package.json` of `"testcafe": "< 0.19.0"` while devDependencies lists `"testcafe": "0.21.1",`. This makes npm error on an install and causes jenkins to fail unless I hide all potential serious errormessages

**Comment by crudo** [comment]
@japrescott Fixed in https://github.com/crudo/grunt-testcafe/releases/tag/v0.22.0
